version: '2'

services:

  webnginx:
    image: jayjohnson/django-nginx:testing
    container_name: "webnginx"
    hostname: "webnginx"
    env_file: 
      - ./testing.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/web:/opt/web
    networks:
      - webstack
  webserver:
    image: jayjohnson/django-slack-sphinx:testing
    container_name: "webserver"
    hostname: "webserver"
    env_file: 
      - ./testing.env
    volumes:
      - /opt/web:/opt/web
    networks:
      - webstack

networks:
  webstack:
    driver: bridge

